name: quizmobileapp
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  web_socket_channel: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/images/

  uses-material-design: true
